### PR TITLE
refactor start scripts and docker

### PR DESCRIPTION
**Pull request by tim-br**
Move all shyft related files to shyft-config directory, with the goal of eventually moving these config files to a separate repo.

For now, these changes mean that on any deployed nodes we can easily modify the config files and restart the containers with docker-compose.

This may change our workflow in the following ways:

- Instead of `sh ./shyft-geth.sh  --start`, developers will need to run `sh shyft-config/shyft-geth.sh  --start` (other bash scripts in shyft-config will have to be run similarly).

Non-breaking changes:

- the shyft-config directory is mounted to the shyftgeth container along with the config.toml files and other config files.

- The script that removes `shyftdb`  from postgres container is removed, so user will have to remove the `pg-data` directory if they want a clean db data directory. This may mean the ./docker/development/pg/Dockerfile is redundant but we may need another wrapper image in the future.

-The genesis block is still created when the container is created (unless the shyftData directory is non-empty), however the ShyftNetwork.json file is now also mounted in the shyft-config dir when the container is created.

To test: Run stack locally and using docker-compose

### CODE REVIEW

**Review by larry-shyft — APPROVED** [review]
The refractor definitely makes the  repo look cleaner, and I totally agree that the shyft-config moved to another private repo

**Comment by dutterbutter** [comment]
I also like this approach, great work guys! @strangepowers 

Built locally fine, however I had to start the miner through the console, I am not sure if that was intentional or not.

**Errored** on `docker-compose build`, specifically copying over `./wait-for-it.sh` for the `shyft_block_api` service.
screen shot 2018-12-17 at 3 09 00 pm

**Comment by tim-br** [comment]
@dutterbutter  should be fixed on latest commit

**Comment by tim-br** [comment]
@dutterbutter  miners should start automatically

**Comment by dutterbutter** [comment]
Builds successfully for me locally and through docker

**Comment by dbkbali** [comment]
1) The readme and github pages documentation needs to be updated to reflect the relocation of files, especially with respect to local startup.

2) Docker build didnt work for me the first time - the reason being I believe that there was a residual shared volume pg-data directory from a previous build. It is possible that this is the reason the docker_init_user_db.sh was used previously, to ensure the shyftdb database that may be in a residual shared volume, is dropped if it exists.

Docker build worked the second time but we may want to add the docker_init_user_db.sh script back to the postgres startup, so other users dont encounter problems as well as updating docs accordingly prior to merge

**Pull request merged**
