### PR TITLE
Tests Green

### PR DESCRIPTION
**Pull request by dbkbali**
Tests Are Green on My machine but still seeing some intermittant random failures - even with parrallel cores set to 2. If tests fail then parrallel cores should be switched to 1 - as we suspect multiple instances are creating race conditions in the sql database adapter. Tests in whisperv5  and console are currently being skipped as these test failures are due to non postgres external dependencies or network file settings which are machine dependent.  We will continue to investigate the skipped tests and the management of postgresql adapter performance in parralel tests as time permits

### CODE REVIEW

**Comment by dbkbali** [comment]
Please hold this merge request until @dutterbutter and I get Circle CI configured correctly, as currently is doesnt appear to be configured to support the postgres database .  However it would be good to see if our testsuite passes on the other reviewers machines

**Comment by ansermino** [comment]
Here are my results, ran `./shyft_geth.sh --setup` followed by `go test ./... -parallel 2 -v`. Do see some errors, but we have had a fair share of issues with my setup before.

https://gist.github.com/ansermino/d33f803dce29e716ec09298aba928256

**Comment by GregTheGreek** [comment]
@dbkbali do we want to use circle or travis?

**Comment by dutterbutter** [comment]
@GregTheGreek go-ethereum seems to be using both Travis and circlecCI

**Comment by ansermino** [comment]
@GregTheGreek @dutterbutter I think they stopped using circleCI, looks like the config has been removed

https://github.com/ethereum/go-ethereum

**Comment by dbkbali** [comment]
I think Circle Ci in the original go-ethereum was used to test the build of docker images ..

**Comment by jaypersanchezshyft** [comment]
I briefly worked with Travis.  I don't know anything about circleCI.

Jayper Sanchez
250-984-1308
jayper@shyft.network.com
Blockchain Developer @Shyft Network

**Comment by dbkbali** [comment]
Closing this branch as @dutterbutter 's branch partially based on this one skips the tests that were problems and passes Travis CI

**Pull request closed without merging**
