### PR TITLE
Refactor References/Imports From ethereum/go-ethereum To ShyftNetwork/go-empyrean

### PR DESCRIPTION
**Pull request by dbkbali**
Refactoring required so we can make geth using the forked repo ShyftNetwork/go-empyrean -for testnet/dev docker containers

### CODE REVIEW

**Comment by GregTheGreek** [comment]
Works on my end.
@dutterbutter & @strangepowers   can you confirm?

**Review by GregTheGreek — APPROVED** [review]

**Review by dutterbutter — APPROVED** [review]

**Comment by dutterbutter** [comment]
works on my end once I changed my path.

**Comment by strangepowers** [comment]
Works for me

**Comment by strangepowers** [comment]
We’ll also need to rebase all of our dev branches.

**Pull request merged**
