### PR TITLE
Removed old dockers

### PR DESCRIPTION
**Pull request by priom**
- Removed old redundant docker files
- Shyft specific dockerfiles naming conventions to get recognized by DockerHub for automated builds

### CODE REVIEW

**Comment by GregTheGreek** [comment]
@priom I'm going to have to close this. please merge this into development.

**Comment by GregTheGreek** [comment]
The workflow is:
Development: For ongoing changes
Staging: Ready for QA
Master: Passed QA

**Comment by priom** [comment]
@GregTheGreek this has to be here...i'm setting up the automated build...

**Comment by GregTheGreek** [comment]
Auto build to docker-hub?

**Comment by priom** [comment]
@GregTheGreek yes, this has to asap, the built is stuck now..the auto-build is going to be from staging branch from now on.

**Comment by GregTheGreek** [comment]
Cool. Will merge.

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
