### PR TITLE
Revert "PG flag inversed"

### PR DESCRIPTION
**Pull request by dbkbali**
Reverts ShyftNetwork/go-empyrean#135

I am reverting this for now - as I believe we should discuss the structuring of this further, specific concerns I have currently are:

1) The code internals have a dependency to an environmental variable set in the travis.yml configuration;

2) Some tests appear to have a specific dependency on connecting to a pg database prior to the test running, if indeed these explict connections in tests are required for them to pass, then this suggests that -  the requirement to have go-empyrean to be able to run without a dependency on postgres has not been achieved.

Lets discuss, and determine whether the code we have here is appropriate.

### CODE REVIEW

**Comment by dutterbutter** [comment]
We can certainly have a further discussion about this. However, to add some narrative to the concerns mentioned above:
- the Travis.yml config environment variable is still being used appropriately, that is ensuring the build is successful without a pg instance
- The tests were a PG instance is being instantiated have been modified with the inverse flag in mind and successfully write to a PG instance where applicable
- All tests and Travis builds were successful in order for this PR to be merged 

Nonetheless, a discussion about further implications can certainly be had. As we had discussed prior to inverting the flag, the postgres instance and block explorer are features that should be enabled by the developer should they want to use them and preferably not on by default.

**Comment by GregTheGreek** [comment]
I think the major issue at hand now that we removed postgres by default we need to re-consider the test suite like @dbkbali mentioned. If the tests pass only because we have postgres instantiated then that is not a true test (assuming it isn't needed)

**Comment by dutterbutter** [comment]
The tests write to the postgres instance during the tests. How else would our own DB tests pass when we are writing specific data to the db and then getting that db for a comparison test. 

Using `core.ConnectPG()` is used within the tests to ensure the db is not only instantiated but the flag protecting the SWriteBlock function in `blockchain.go` (ie.`if GlobalPG == "connected" `), is true allows for blocks to be written to the db. If it wasn't writing to the db for tests then our tests would have failed. 

The possible implications I see are maybe within the docker images.

**Comment by dbkbali** [comment]
I have no issue with the Travis build - but the application code shouldn't be dependent on a flag in a travis config file - the file geth/chaincmd.go func initGenesis - explicitly looks up the travis.yml variable when it shouldn't need too - as the core software code in my view should be able to run independently of the travis config.

Further there are some tests - that are not testing any pg related code - that have code connecting to a pg database (eg. TestBlockSubscription, TestClique ), obviously tests that are specific to requiring a pg connection do need a connection. But there is no apparent reason the foregoing tests should need this.

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
