### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by tim-br**
Update readme with more empyrean specific details.

### CODE REVIEW

**Comment by ansermino** [comment]
Just a suggestion -- a more directive issue template with some instructions might save time down the road. Maybe check out https://raw.githubusercontent.com/ShyftNetwork/shyft_ganache-core/develop/ISSUE_TEMPLATE.md for some inspiration.

**Comment by tim-br** [comment]
Good suggestion -- I update the issue template.

**Review by GregTheGreek — APPROVED** [review]

**Review by GregTheGreek — CHANGES_REQUESTED** [review]
Not sure why... But the CI is failing...

**Comment by amerameen** [comment]
Any idea why this is failing? @strangepowers

**Comment by ansermino** [comment]
@amerameen @strangepowers These tests do fail sporadically. Just re-ran, if it fails again we should retry once more before considering it a true fail.

**Pull request merged**
