### PR TITLE
Development

### LINKED ISSUE #77: Block Explorer UI only displays records when accessing from localhost
Hi Team,

When accessing from outside the server itself, the Block Explorer UI does not connect to the Block Explorer API correctly.

#### System information

Geth version: shyftgeth 1.8.3
OS & Version: Ubuntu 16.04

#### Expected behaviour
The Block Explorer UI should display records about transactions, accounts, and blocks.

#### Actual behaviour
The Block Explorer UI displays empty records.

#### Steps to reproduce the behaviour
clone the repo
docker-compose up -d 
access block explorer ui using a browser not on the server itself

#### Backtrace

WebSocket connection to 'ws://ec2-18-204-231-31.compute-1.amazonaws.com/sockjs-node/988/3qcqilyg/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WebSocketBrowserDriver @ websocket.js:6
WebSocketTransport @ websocket.js:32
./node_modules/sockjs-client/lib/main.js.SockJS._connect @ main.js:219
./node_modules/sockjs-client/lib/main.js.SockJS._receiveInfo @ main.js:193
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
(anonymous) @ info-receiver.js:67
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
(anonymous) @ info-ajax.js:37
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
xhr.onreadystatechange @ abstract-xhr.js:124

@GregTheGreek @dbkbali @dutterbutter @strangepowers @chris-shyft @priom

### PR DESCRIPTION
**Pull request by GregTheGreek**
This PR closes #77, #78 & #83.

Major Changes:
- Adds support for the V1 of the Rollback functionality
- Cleans up the docker images
- Adds optional db flag
- Upgrades to the postgres data fields and types (#78)
- Shyft core functions tested and are green.

Note:
The core ethereum tests (https://github.com/shyftnetwork/shyft_tests) are failing, ~80 tests, due to having postgres implemented into the repo. This is a WIP and will take another week to get done. 
The goal for this section is to have @larry-shyft test syncing nodes as well as to execute a rollback within a cluster of nodes running on the network.

I will need approval from @NikkiS713 @jaypersanchezshyft @larry-shyft before we proceed with merging this. Once all approvals are in we can go ahead with getting larry to update the nodes that are live.

### CODE REVIEW

**Review by NikkiS713 — APPROVED** [review]
[Shyft Network - Go-Empyrean - Issues Report.pdf](https://github.com/ShyftNetwork/go-empyrean/files/2448010/Shyft.Network.-.Go-Empyrean.-.Issues.Report.pdf)

**Review by larry-shyft — APPROVED** [review]
Tested branch with respect to Issue 77, 78, 83. All passed

**Comment by GregTheGreek** [comment]
@dutterbutter @dbkbali @priom we have a few conflicts. Once fixed ill merge.

**Comment by dbkbali** [comment]
Fixed conflicts

**Pull request merged**
