### PR TITLE
cmd, core, params: add support for Goerli

### PR DESCRIPTION
**Pull request by tim-br**
The objective of the PR is to enable goerli testnet support right out of the box. This will allow any user of go-empyrean to easily connect to goerli for testing.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
Is this the upstream PR or was this custom? @strangepowers

**Comment by dutterbutter** [comment]
Everything is working on my end. @dbkbali @GregTheGreek can you confirm?

**Review by GregTheGreek — DISMISSED** [review]

**Comment by GregTheGreek** [comment]
Can't approve this yet, need rational for having goerli in shyft.... Especially since it hasn't made it upstream yet.

@strangepowers

**Comment by tim-br** [comment]
Useful for testing.

**Comment by GregTheGreek** [comment]
I believe Goerli has been merged already. Closing.

**Pull request closed without merging**
