### PR TITLE
Tests passing in Travis

### PR DESCRIPTION
**Pull request by dutterbutter**
To run the tests on your machine please follow the below instructions:
- Delete any shyft dbs present
- `go clean -testcache`
- `go test ./... -parallel 2`

@dbkbali and I have completed the initial testing, where both geth and our own tests are passing. There are limitations, however, as follows:

- Skipping tests in ./console directory --> _Still trying to diagnosis the issue_
- Skipping tests in peer_test.go --> _Still trying to diagnosis the issue_
- Skipping test `testGetCHTProofs` in `handler_test.go` --> _Still trying to diagnosis the issue_
- A requirement of running `-parallel 2` test flag due to the parallelism of tests and the pg database

@dbkbali has been working on a solution to `-parallel 2` issue in order to speed up tests. Currently, the tests take ~18mins in travis to build/run successfully. 

**The tests are passing in Travis** from this branch, please review [travis build](https://travis-ci.org/ShyftNetwork/go-empyrean/builds/448536609)

**Changes made in this pull request:**

- Updated folder structure and moved shyft database files into ethdb, and core shyft files into core in order to be more aligned with current go-ethereum implementation
- Set default genesis block to be ShyftNetwork.json (_ie. no longer need to run **-setup** script, just -**-start** ....unless you want to start a new chain then still **--reset** then **--start**_)
- The shyft database now runs in parallel with the leveldb instance, meaning when a leveldb instance is expected the shyftdb is also expected
- Modified the geth tests to account for the above change in structure
- Modified our own shyft database tests 
- Updated the `--disablepg` flag --> This allows users to run the node without a postgres instance
- Modified the travis.yml file, specifically indicating usage of postgres 9.6, as Travis-cli postgres 10 implementation has many issues associated with it, the creation of two postgres databases, and installing the go dependencies

### CODE REVIEW

**Comment by dbkbali** [comment]
Hey @dutterbutter great for pulling this together and getting Travis running - I will check this tomorrow am.

**Comment by dbkbali** [comment]
Dustin I am getting the following failure in your branch running 

```
go test -p 2 ./... v 

```

PASS | SignEncodeAndDecodeRandom (0.00s)
PASS | github.com/ShyftNetwork/go-empyrean/p2p/enr 0.033s
START| AutoDiscRace
PASS | AutoDiscRace (0.50s)
START| UPNP_DDWRT
FAIL | --- FAIL: TestUPNP_DDWRT (2.10s)
     | 	natupnp_test.go:165: not discovered
FAIL | 	github.com/ShyftNetwork/go-empyrean/p2p/nat	2.625s
START| IsPacketTooBig
PASS | IsPacketTooBig (0.00s)
START| ParseNetlist
PASS | ParseNetlist (0.00s)

and more failures with unlimited cores..

Should we skip this test for now? as well on Travis - before we finalize  it would be good to know what failures others are experiencing if any? maybe @strangepowers and @ansermino can run these on there machines, as it could be a failure due to a specific firewall/port issue

**Comment by dutterbutter** [comment]
@dbkbali yes you will experience failures when running with unlimited cores, as for the `TestUPNP_DDWRT` test failure it would be interesting to see if others experience the same issue as it could be a firewall/port difference.....since Travis is passing it leads me to believe its machine specific but I could be wrong. Nonetheless, I could look into it in greater detail.

**Comment by dbkbali** [comment]
@dutterbutter should we close this until we have circle ci/travis working? Or do you want me to continue to review?

**Pull request closed without merging**
