### PR TITLE
Upstream changes, db refactor and tests passing

### PR DESCRIPTION
**Pull request by dutterbutter**
**Changes made in this pull request:**

This is a large PR as it contains all the changes from upstream (~1000 commits)

- Tests refactored to account for postgres instance
- `--disablepg` flag refactored to tie in directly with eth.config
- Travis is set up and passing [TRAVIS SUCCESS](https://travis-ci.org/ShyftNetwork/go-empyrean/builds/452507979?utm_source=github_status&utm_medium=notification)
- default genesis is now ShyftNetwork.json
- updated folder structure to eliminate go import cycles

**Please run the following to ensure no breaking changes:**
- `make geth`
- Ensure no shyft dbs already exist on your machine
- `./shyft-geth.sh --reset ` 
- `./shyft-geth.sh --start`
- Once geth starts check your db to ensure the correct genesis accounts, block 0 and txs have been recorded
- open a new terminal, navigate to ShyftNetwork directory on your machine and run `go run shyftBlockExplorerApi/*.go` // this will start up the api server
- open a new terminal, navigate to ShyftNetwork directory on your machine and run `cd shyftBlockExplorerUI` and then `npm install` and then `npm run start` 
- Select Blocks, Accounts, Transactions to make sure API and UI are functioning correctly
- Send internal transactions through geth by navigating into `shyft-cli/web3/transfer-through-master` and then running `truffle migrate`
- Ensure internal transactions are being recorded correctly in the postgres database

### CODE REVIEW

**Comment by GregTheGreek** [comment]
What should I run to test this works?
Edit:
Is the test suite passing enough @dbkbali @dutterbutter

**Comment by dutterbutter** [comment]
@GregTheGreek updated PR with instructions to make sure no breaking changes

**Comment by GregTheGreek** [comment]
My go modules are broken i think...

Hopefully I can get that finished soon.

**Comment by GregTheGreek** [comment]
@dutterbutter Looks like travis is failing, I'm currently removing circle

**Comment by GregTheGreek** [comment]
Removed, circle. If you make a new push it should no longer have it.

**Review by dbkbali — APPROVED** [review]
Dustin - all is good on my machine, great job in upgrading all the commits.

In terms of todo's which can be done prior to merging development to staging - I think we need to look at rewriting the readme, specifically with sections related to testing & contributing - and reviewing whether we need all of the parts of the readme that were specific to geth, including a note about turning any firewalls off when running tests locally (as I need this to get the test suite to pass on my machine).Let me know how I can contribute here. 

Also, looks like this might have fixed this issue, https://github.com/ShyftNetwork/go-empyrean/issues/116 (fixes #116). 

Development Docker images all built successfully on my machine.

**Comment by tim-br** [comment]
All is good on my machine.

**Review by tim-br — APPROVED** [review]
Reviewed and tested locally.

**Pull request merged**
